In [ ]:
import tensorflow as tf

# Regression

## 1. Mean Squared Error

In [ ]:
y_true = [[100]]
y_pred = [[80]]

mse = tf.keras.losses.MeanSquaredError()
mse(y_true,y_pred)

<tf.Tensor: shape=(), dtype=int32, numpy=400>

# 2. Mean Absolute Error

In [ ]:
y_true = [[100]]
y_pred = [[80]]

mae = tf.keras.losses.MeanAbsoluteError()
mae(y_true,y_pred)

<tf.Tensor: shape=(), dtype=int32, numpy=20>

# Classification

### 1. Binary Cross Entropy

 Entropy is used if the output emitted from any instance is a prob value (0 to 1)

In [ ]:
y_true = [[1]]
y_pred = [[0.7]]

In [ ]:
import numpy as np
-( (1 * np.log(0.7)) + (1-1) * np.log(1-0.7))

0.35667494393873245

In [ ]:
#bce = tf.keras.losses.binary_crossentropy
#bce(y_true,y_pred)
#Check in Colab

### 2. Categorical Cross Entropy

In [ ]:
y_true = [[0,1,0]]
y_pred = [[0.05,0.95,0.000000000000001]]

In [ ]:
-( (0 * np.log(0.05)) + (1 * np.log(0.95)) + (0 * np.log(0.000000000000001)))

0.05129329438755058

In [ ]:
cce = tf.keras.losses.CategoricalCrossentropy()
cce(y_true,y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=0.051293306>